### ISSUE TITLE
Create About Page

### ISSUE THREAD

**Issue by Lencho2012** [shahwaiz14/shahwaiz14.github.io#2]
Should include:

- Group name
- Group members with: name, photo, bio and project responsibilities
- Stats: total issues, link to -> issue tracker, repo and wiki
- Tools used

**Comment by Lencho2012** [comment]
Angel Bio: Born Austin, TX. History Major, Computer Science Minor. I PTFO in Battlefield, give my kitty lots of hugs and relax to the sounds of screams in heavy metal music.

**Comment by mkay110** [comment]
Mehlum Bio:

Born in Chicago IL, Advertising major, CS and Business foundations certificates. I have never broken a bone, and I am your mom's favorite son. 

I created the categories instances.

**Comment by shahwaiz14** [comment]
Name: Shahwaiz Punjwani
Bio : I am from Houston, Texas. I am majoring in Mathematics with a concentration in Scientific Computing.
Project Responsibilities: Created the splash page and model pages.

**Comment by Lencho2012** [comment]
Need stats info.

**Comment by Lencho2012** [comment]
Complete
